### ISSUE TITLE
Lubridate error due to leapday + suggestion of using multiple en dates

### ISSUE THREAD

**Issue by gforge** [rOpenGov/sweidnumbr#72] opened 2015-09-06 09:39 UTC
Leap day issue
============

It seems that leap days are causing issues. Although this [should be fixed](https://github.com/hadley/lubridate/issues/235) in the lubridate package this is not entirely the case, the following throws an error:

```R
int <- new("Interval"
    , .Data = 2121342802
    , start = structure(-1446595200, class = c("POSIXct", "POSIXt"), tzone = "UTC")
    , tzone = "UTC"
)

tspan <- new("Period"
             , .Data = 0
             , year = 1
             , month = 0
             , day = 0
             , hour = 0
             , minute = 0
)

int%/%tspan
```

```
Error in while (any(start + est * per < end)) est[start + est * per <  : 
  missing value where TRUE/FALSE needed
```

Multiple dates
===========

I suggest that you add the option of having multiple end dates, this is useful when calculating the time to event data.

Suggested solution
===============

The following change the pin_age use the lubridate:::as.period() together with an option of having end dates specified:

```R
pin_age <- function (pin, date = Sys.Date(), timespan = "years") 
{
  if (length(date) == 1) {
    message("The age has been calculated at ", as.character(date), 
            ".")
  } 
  else if (length(date) == length(pin)){
    message("The age is calculated relative to the '", deparse(substitute(date)), "' date")
  }
  else {
    stop("Multiple dates used.")
  }
  date <- as.Date(date)
  if (!is.pin(pin)) 
    pin <- as.pin(pin)
  all_pins <- pin
  pin <- all_pins[!is.na(all_pins)]
  diff <- lubridate::interval(pin_to_date(pin), lubridate::ymd(date))
  timespan_lubridate <- switch(timespan, years = lubridate::years(1), 
                               months = lubridate::new_period(month = 1), weeks = lubridate::weeks(1), 
                               days = lubridate::days(1))
  age <- as.integer(lubridate:::as.period(diff)%/%timespan_lubridate)
  if (any(age < 0)) 
    warning("Negative age(es).")
  all_age <- rep(as.integer(NA), length(all_pins))
  all_age[!is.na(all_pins)] <- age
  all_age
}
```

**Comment by MansMeg** [comment] 2015-09-06 13:21
Hi Max!

Thanks for the suggestions! Regarding leapyear this is a known bug (see #26 ). The problem is fixed in lubridate 1.4 (the test cases of sweidnumbr passes) but lubridate 1.4 has not (yet) been published on CRAN. So as soon lubridate is published on CRAN this will problem will go away. If you download the latest version of lubridate this will work for you.

Regarding multiple time periods I think it is a good idea to implement it in a vectorized form. Is it possible to for the repo and add it using a merge request? The all testsuites will be run and we can see if it will make any test cases fail?

/Måns

**Comment by MansMeg** [comment] 2015-09-07 05:23
Great job!

**Closed by MansMeg** 2015-09-07 05:23 UTC

**Comment by eribul** [comment] 2015-09-07 09:47
Hi there @gforge!
Nice to see your name showing up here!
You probably don't know me but I am actually reading your phd thesis right now :-)
I work in the same building as Göran G and am a close friend to Szilard!
